Repository odoo/odoo-ls, pull requests merged in 2025-01, with the labels that each got.

#173 [IMP] server: avoid rebuild of invalid file with onSave setting
  server/src/core/odoo.rs
Labels: bug, enhancement

#182 [FIX] server: do not raise diagnostic OLS30322 for Properties fields
  server/src/core/evaluation.rs
Labels: enhancement

#187 [IMP] vscode: remove await LSCLIENT.start() in activate extension method
  vscode/client/extension.ts
Labels: enhancement

#189 [FIX] server: crash on compiled files importation
  server/src/core/import_resolver.rs
  server/src/core/python_arch_builder.rs
Labels: bug

#188 [FIX] client: Default value for disablePythonLanguageServer
  vscode/client/common/validation.ts
  vscode/client/extension.ts
  vscode/package.json
Labels: enhancement

#185 Remove Odoo/getPythonPath route and use config information
  server/src/core/config.rs
  server/src/core/odoo.rs
  vscode/client/extension.ts
  vscode/client/global.d.ts
  vscode/tsconfig.json
Labels: enhancement

#190 [FIX] vscode: compute finalPythonPath on config save
  vscode/client/common/utils.ts
  vscode/client/extension.ts
  vscode/client/views/configurations/configurationWebView.ts
Labels: bug
