Repository odoo/odoo-ls, pull requests merged in 2025-02, with the labels that each got.

#193 [FIX] server: improve messages managements to not block threads and b…
  server/src/constants.rs
  server/src/core/odoo.rs
  server/src/main.rs
  server/src/server.rs
  server/src/threads.rs
Labels: bug

#195 [IMP] server: use start of expr for scope completion
  server/src/features/completion.rs
Labels: bug

#198 [IMP] server, vscode: remove afterDelay option
  server/src/core/config.rs
  server/src/core/odoo.rs
  vscode/client/extension.ts
  vscode/client/migration/migrateConfig.ts
  vscode/package.json
Labels: enhancement

#200 [IMP] server: hide logs from process_rebuild behind DEBUG_THREAD option
  server/src/constants.rs
  server/src/core/odoo.rs
  server/src/core/python_arch_builder.rs
  server/src/core/python_arch_eval.rs
  server/src/core/python_odoo_builder.rs
  server/src/core/python_validator.rs
Labels: enhancement

#199 [FIX] server: remove autocompletion items that are not in dependencies
  server/src/core/symbols/symbol.rs
  server/src/threads.rs
Labels: enhancement

#204 0.4.0
  CHANGELOG.md
  server/Cargo.toml
  server/src/constants.rs
  vscode/noxfile.py
  vscode/package.json
Labels: documentation

#207 [IMP] server: validate missing statements
  server/src/core/python_validator.rs
Labels: enhancement

#210 [IMP] readme: add vim integration link
  README.md
Labels: documentation

#209 [FIX] server: do not try to evaluate file with no path on disk
  server/src/core/odoo.rs
Labels: bug

#217 [IMP] server: answer Document Symbol requests
  server/src/core/odoo.rs
  server/src/features/document_symbols.rs
  server/src/features/mod.rs
  server/src/server.rs
  server/src/threads.rs
Labels: enhancement

#214 [FIX] server: avoid unwrap on base class werak upgrade
  server/src/core/symbols/symbol.rs
Labels: bug

#213 [FIX] server: avoid to do arch eval if text hash is different
  server/src/core/python_arch_eval.rs
Labels: bug

#212 [FIX] server: unload_path of file outside of workspace
  server/src/core/odoo.rs
Labels: bug

#216 [FIX] server: URL encode path before parsing
  server/src/core/file_mgr.rs
Labels: bug

#218 [FIX] server: test if odoo package is found or not
  server/src/core/odoo.rs
Labels: bug

#219 [IMP] server: implement basic match pattern evaluation
  server/src/core/python_arch_builder.rs
  server/src/core/python_arch_eval.rs
  server/src/features/ast_utils.rs
Labels: enhancement

#220 [FIX] server: push empty diagnostics to reset file diagnostics
  server/src/core/file_mgr.rs
Labels: bug

#223 [FIX] server: implement custom visitors for Document Symbols feature
  server/src/core/odoo.rs
  server/src/features/document_symbols.rs
Labels: enhancement

#221 [IMP] server: handle while statements in arch(eval)
  server/src/core/python_arch_builder.rs
  server/src/core/python_arch_eval.rs
  server/src/features/ast_utils.rs
Labels: enhancement

#224 [FIX] server: better error message in case of missing typeshed
  server/src/core/odoo.rs
Labels: enhancement

#227 [FIX] server: fix follow_ref stop on type
  server/src/core/symbols/symbol.rs
Labels: bug

#230 [IMP] server: handle new odoo structure on > 18.1
  server/src/core/odoo.rs
  server/src/core/symbols/file_symbol.rs
  server/src/core/symbols/symbol.rs
Labels: bug

#226 [FIX] server: fix test_mode ctx and testcursor eval
  server/src/core/evaluation.rs
  server/src/core/python_arch_eval_hooks.rs
  server/src/core/symbols/symbol.rs
Labels: enhancement

#229 [FIX] server: detect cycles on evaluating assignment stmts
  server/src/core/python_arch_eval.rs
Labels: bug

#225 0.4.1
  CHANGELOG.md
  server/Cargo.toml
  server/src/constants.rs
  vscode/package.json
Labels: documentation
