Repository odoo/odoo-ls, pull requests merged in 2025-08, with the labels that each got.

#352 [IMP] server: completion of inherits model attr
  server/src/features/completion.rs
Labels: enhancement

#363 [IMP] vscode: set serverConfigPath and restart on update
  vscode/client/extension.ts
  vscode/package.json
Labels: enhancement

#366 [IMP] vscode: build zip files
  vscode/noxfile.py
Labels: packaging

#372 Master context fix fda
  server/src/core/python_arch_eval_hooks.rs
Labels: bug

#374 0.10.2
  changelog.md
  server/Cargo.toml
  server/src/constants.rs
  vscode/package.json
Labels: documentation

#376 [IMP] server: use current_exe instead of current_dir in config
  server/src/core/odoo.rs
Labels: enhancement

#379 [REF] Remove vscode code to move it to its own repository
  .gitignore
  vscode/.eslintrc.yml
  vscode/.vscode/launch.json
  vscode/.vscode/settings.json
  vscode/.vscode/tasks.json
  vscode/.vscodeignore
  vscode/COPYRIGHT
  vscode/LICENSE
  vscode/README.md
  vscode/SECURITY.md
  vscode/build_package.sh
  vscode/client/common/cleanup.mjs
  vscode/client/common/constants.ts
  vscode/client/common/events.ts
  vscode/client/common/python.ts
  vscode/client/common/safeLanguageClient.d.ts
  vscode/client/common/safeLanguageClient.js
  vscode/client/common/utils.ts
  vscode/client/common/validation.ts
  vscode/client/extension.ts
  vscode/client/global.d.ts
  vscode/client/migration/migrateConfig.ts
  vscode/client/views/changelog/body.html
  vscode/client/views/changelog/changelogWebview.ts
  vscode/client/views/changelog/style.css
  vscode/client/views/crash_report/body.html
  vscode/client/views/crash_report/crashReport.ts
  vscode/client/views/crash_report/script.js
  vscode/client/views/crash_report/style.css
  vscode/client/views/welcome/style.css
  vscode/client/views/welcome/welcomeAlertView.html
  vscode/client/views/welcome/welcomeWebView.html
  vscode/client/views/welcome/welcomeWebView.js
  vscode/client/views/welcome/welcomeWebView.ts
  vscode/images/advanced_hover_def.gif
  vscode/images/autocomplete.png
  vscode/images/autocompletion2.png
  vscode/images/autocompletion3.png
  vscode/images/autocompletion4.png
  vscode/images/autocompletion5.png
  vscode/images/diagnostics.png
  vscode/images/diagnostics2.png
  vscode/images/help_1.png
  vscode/images/help_2.png
  vscode/images/help_3.png
  vscode/images/odoo_favicon
  vscode/images/odoo_logo.png
  vscode/noxfile.py
  vscode/package.json
  vscode/tsconfig.json
  vscode/vscode.code-workspace
Labels: documentation

#385 [FIX] server: ensure ctx values have the right type
  server/src/core/python_arch_eval_hooks.rs
Labels: bug
