Repository odoo/odoo-ls, pull requests merged in 2025-07, with the labels that each got.

#327 various diagnostics fixs
  server/src/core/python_arch_eval_hooks.rs
Labels: bug

#330 [FIX] server: crash on invalid Class AST
  server/src/core/python_arch_builder.rs
Labels: bug

#325 XML Support - Part 1b
  server/error_code.md
  server/src/core/evaluation.rs
  server/src/core/python_arch_builder.rs
  server/src/core/python_arch_builder_hooks.rs
  server/src/core/python_arch_eval_hooks.rs
  server/src/core/python_odoo_builder.rs
  server/src/core/symbols/module_symbol.rs
  server/src/core/symbols/symbol.rs
  server/src/core/xml_arch_builder.rs
  server/src/core/xml_arch_builder_rng_validation.rs
Labels: enhancement

#335 [IMP] vscode, server: automation build scripts
  .gitignore
  server/Cross.toml
  server/build.sh
  vscode/build_package.sh
  vscode/client/extension.ts
  vscode/noxfile.py
Labels: documentation, packaging

#350 [FIX] server: follow ref for decs and version check
  server/src/core/python_arch_eval_hooks.rs
  server/src/features/completion.rs
  server/src/features/features_utils.rs
  server/tests/test_get_symbol.rs
  server/tests/test_utils.rs
Labels: bug

#355 [FIX] server: fix case sensitive test
  server/tests/config_tests.rs
Labels: bug

#353 [IMP] server: add diagnostic for model shadowing
  server/src/core/diagnostic_codes_list.rs
  server/src/core/python_odoo_builder.rs
Labels: enhancement
