Repository odoo/odoo-ls, pull requests merged in 2025-04, with the labels that each got.

#269 [IMP] server: prevent follow_ref from looping in cyclic evaluations
  server/src/core/symbols/symbol.rs
Labels: bug

#274 [IMP] server: support for noqa
  server/src/core/evaluation.rs
  server/src/core/file_mgr.rs
  server/src/core/import_resolver.rs
  server/src/core/python_arch_builder.rs
  server/src/core/python_arch_eval.rs
  server/src/core/python_arch_eval_hooks.rs
  server/src/core/python_validator.rs
  server/src/core/symbols/class_symbol.rs
  server/src/core/symbols/file_symbol.rs
  server/src/core/symbols/function_symbol.rs
  server/src/core/symbols/module_symbol.rs
  server/src/core/symbols/package_symbol.rs
  server/src/core/symbols/symbol.rs
  server/src/threads.rs
Labels: enhancement

#277 [IMP] server: Detect duplicated manifest keys
  server/error_code.md
  server/src/core/symbols/module_symbol.rs
Labels: enhancement

#272 [IMP] server: improve reactivity of rebuilds on typing
  server/src/core/odoo.rs
  server/src/server.rs
  server/src/threads.rs
Labels: bug

#280 [IMP] server: Raise error diagnostic on modifying fields in compute
  server/src/core/model.rs
  server/src/core/python_arch_eval.rs
  server/src/core/python_arch_eval_hooks.rs
  server/src/core/python_odoo_builder.rs
  server/src/core/python_validator.rs
  server/src/core/symbols/variable_symbol.rs
Labels: enhancement

#281 [FIX] server: do not return a class name if the ast does not contain it
  server/src/features/document_symbols.rs
Labels: bug

#278 [IMP] server: move decorator handlers to hooks
  server/src/core/python_arch_eval.rs
  server/src/core/python_arch_eval_hooks.rs
Labels: enhancement

#279 [FIX] server: Fix related field type diagnostic
  server/src/core/python_validator.rs
Labels: bug

#284 [FIX] server: fix deleting path of opened files
  server/src/core/file_mgr.rs
  server/src/core/import_resolver.rs
  server/src/core/python_arch_eval.rs
Labels: bug

#285 [DOC] server: add compute diagnostic description
  server/error_code.md
Labels: documentation

#286 [FIX] server: Fix file manager clear borrow error
  server/src/core/file_mgr.rs
Labels: bug

#287 [IMP] server: update message for OLS30323
  server/error_code.md
  server/src/core/python_arch_eval_hooks.rs
  server/src/core/python_validator.rs
Labels: documentation

#270 0.6.0
  changelog.md
  server/Cargo.toml
  server/src/constants.rs
  vscode/package.json
Labels: documentation

#290 [FIX] vscode: only clear diagnostics when paths change
  vscode/client/extension.ts
Labels: bug, enhancement

#293 [FIX] server: fix crash on refresh evaluation
  server/src/core/entry_point.rs
  server/src/core/odoo.rs
Labels: bug

#292 [IMP] server, vscode: new option to choose if files should be kept in…
  server/src/allocator.rs
  server/src/core/config.rs
  server/src/core/file_mgr.rs
  server/src/core/odoo.rs
  server/src/core/python_arch_builder.rs
  server/src/core/python_arch_eval.rs
  server/src/core/python_validator.rs
  server/src/core/symbols/module_symbol.rs
  server/src/features/ast_utils.rs
  server/src/features/completion.rs
  server/src/features/document_symbols.rs
  server/src/lib.rs
  server/src/main.rs
  vscode/package.json
Labels: enhancement

#294 [FIX] server: fix transformed path for addons paths
  server/src/core/entry_point.rs
  server/src/core/import_resolver.rs
Labels: bug

#295 [FIX] server: no entrypoint for namespaces
  server/src/core/entry_point.rs
  server/src/core/odoo.rs
Labels: bug

#297 [FIX] server: fix files not marked as closed
  server/src/core/odoo.rs
Labels: bug

#298 [IMP] server,vscode: set default file cache setting to true
  server/src/core/config.rs
  vscode/package.json
Labels: enhancement

#299 0.6.1
  changelog.md
  server/Cargo.toml
  server/src/constants.rs
  vscode/package.json
Labels: documentation

#301 [FIX] server: fix crash if autocompletion is after an empty list of stmt
  server/src/features/completion.rs
Labels: bug

#302 [FIX] server: borrow error on completion if a rebuild is required
  server/src/features/completion.rs
Labels: bug

#306 0.6.2
  changelog.md
  server/Cargo.toml
  server/src/constants.rs
  vscode/package.json
Labels: enhancement

#311 [IMP] server,vscode: package pdb files for clear TBs
  vscode/client/extension.ts
  vscode/noxfile.py
Labels: bug, enhancement

#310 [FIX] server: fix build from hover borrow error
  server/src/features/ast_utils.rs
Labels: bug
