Repository odoo/odoo-ls, pull requests merged in 2025-03, with the labels that each got.

#241 [IMP] server: terminate mechanism for rebuilds during shutdown
  server/src/core/odoo.rs
  server/src/server.rs
Labels: enhancement

#238 Handle extra expressions
  server/src/core/evaluation.rs
Labels: bug, enhancement

#206 [FIX] server: unique results in model name hover
  server/Cargo.toml
  server/src/features/features_utils.rs
Labels: bug, enhancement

#246 [FIX] server: fix get_symbol missing arg
  server/src/core/evaluation.rs
Labels: bug

#243 Remove testCursoe hooks and add env.Registry hooks
  server/src/core/evaluation.rs
  server/src/core/python_arch_builder_hooks.rs
  server/src/core/python_arch_eval_hooks.rs
Labels: enhancement

#244 [IMP] server: evaluate typing.Self function return annotation
  server/src/core/evaluation.rs
  server/src/core/python_arch_eval.rs
Labels: enhancement

#236 [FIX] server: fix removing cyclic evaluations
  server/src/core/python_arch_eval.rs
Labels: bug

#248 [IMP] server: allow hover and gotodefinition features in .pyi
  server/src/core/evaluation.rs
Labels: enhancement

#253 Master tests 2 fda
  server/.vscode/launch.json
  server/src/core/python_arch_builder.rs
  server/src/core/symbols/symbol.rs
  server/tests/setup/setup.rs
  server/tests/test_ls.rs
Labels: enhancement

#259 Master master fda
  server/Cargo.toml
  server/src/constants.rs
  server/src/core/entry_point.rs
  server/src/core/import_resolver.rs
  server/src/core/model.rs
  server/src/core/odoo.rs
  server/src/core/python_arch_builder.rs
  server/src/core/python_arch_builder_hooks.rs
  server/src/core/python_arch_eval.rs
  server/src/core/python_arch_eval_hooks.rs
  server/src/core/python_odoo_builder.rs
  server/src/core/python_validator.rs
  server/src/core/symbols/class_symbol.rs
  server/src/core/symbols/compiled_symbol.rs
  server/src/core/symbols/disk_dir_symbol.rs
  server/src/core/symbols/file_symbol.rs
  server/src/core/symbols/function_symbol.rs
  server/src/core/symbols/module_symbol.rs
  server/src/core/symbols/namespace_symbol.rs
  server/src/core/symbols/package_symbol.rs
  server/src/core/symbols/root_symbol.rs
  server/src/core/symbols/symbol.rs
  server/src/core/symbols/symbol_mgr.rs
  server/src/core/symbols/variable_symbol.rs
  server/src/features/completion.rs
  server/src/features/definition.rs
  server/src/features/features_utils.rs
  server/src/utils.rs
  server/tests/test_basics.rs
  server/tests/test_ls.rs
  server/tests/test_setup.rs
Labels: enhancement

#260 [FIX] server: fix the addition of dependents
  server/src/core/symbols/symbol.rs
Labels: bug

#254 [FIX] server: fix get_all_inferred_names to get correct completion
  server/src/core/symbols/symbol.rs
  server/src/features/completion.rs
Labels: bug

#249 [IMP] server: infer names in outer scope later in file
  server/src/core/python_arch_builder.rs
  server/src/core/python_arch_eval.rs
  server/src/core/symbols/symbol.rs
Labels: enhancement

#262 [FIX] server: avoid duplicated function evals
  server/src/core/evaluation.rs
  server/src/core/symbols/function_symbol.rs
  server/src/core/symbols/symbol.rs
Labels: bug

#261 [FIX] server: fix community path in tests
  server/tests/test_setup.rs
Labels: bug

#263 [DOC] vscode: update readme with more pictures
  vscode/README.md
  vscode/images/advanced_hover_def.gif
  vscode/images/autocompletion2.png
  vscode/images/autocompletion3.png
  vscode/images/autocompletion4.png
  vscode/images/autocompletion5.png
  vscode/images/diagnostics2.png
  vscode/images/goto.gif
  vscode/images/hover.png
Labels: documentation
