Repository odoo/odoo-ls, pull requests merged in 2025-09, with the labels that each got.

#394 [FIX] config: fix addon auto detection
  server/src/core/config.rs
Labels: bug

#397 [IMP] core: upgrade Rust to 2024 edition
  server/Cargo.toml
  server/benches/iai_profiler.rs
  server/src/allocator.rs
  server/src/core/config.rs
  server/src/core/evaluation.rs
  server/src/core/python_arch_builder.rs
  server/src/core/python_arch_eval.rs
  server/src/core/symbols/symbol.rs
  server/src/core/xml_data.rs
  server/src/features/ast_utils.rs
  server/src/features/features_utils.rs
  server/src/main.rs
Labels: enhancement

#399 [IMP] remove read thread
  server/src/server.rs
  server/src/threads.rs
Labels: bug, enhancement

#405 [IMP] allow multiple paths in diagnostic filters
  server/src/core/config.rs
  server/src/core/file_mgr.rs
Labels: enhancement

#408 1.0.0
  changelog.md
  server/Cargo.toml
  server/src/constants.rs
Labels: documentation
